org.gradle.jvmargs=-Xmx4096M -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-Xmx2048M

android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true

# Fix Kotlin daemon crash
kotlin.incremental=false
kotlin.daemon.enabled=true

# Improve build stability
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true